# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'redsloop/CentOS-7.2.1511'

  config.ssh.insert_key = false

  config.vm.network 'forwarded_port', guest: 80, host: 65_434

  config.vm.network 'private_network', ip: '192.168.177.177'

  config.vm.provision 'ansible_local', run: 'always' do |ansible|
    ansible.playbook = './ansible/playbook/main.yml'
    ansible.inventory_path = './ansible/hosts/hosts.yml'
    ansible.config_file = './ansible/ansible.cfg'
    ansible.limit = 'all'
  end
end
