# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.33.77"

  config.vm.provision "ansible_local", run: "always" do |ansible|
    ansible.playbook = "./ansible/playbook/main.yml"
    ansible.inventory_path = "./ansible/hosts/hosts.yml"
    ansible.config_file = "./ansible/ansible.cfg"
    ansible.limit = "all"
  end

end
